# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: trepmag.rest::lang.settings.label

# Model Form Field configuration
form: $/trepmag/rest/models/setting/fields.yaml

# Model Class name
modelClass: Trepmag\Rest\Models\Setting

# Default redirect location
defaultRedirect: trepmag/rest/settings